export enum HOTEL_ACTIONS {
  GET_HOTEL_LIST = "GET_HOTEL_LIST",
  GET_HOTEL_LIST_SUCCESS = "GET_HOTEL_LIST_SUCCESS",
  GET_HOTEL_LIST_PENDING = "GET_HOTEL_LIST_PENDING",
  GET_HOTEL_LIST_REJECTED = "GET_HOTEL_LIST_REJECTED",
  UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS"
}
