export enum HOTEL_ACTIONS {
  GET_HOTEL_LIST = "GET_HOTEL_LIST",
  GET_HOTEL_LIST_SUCCESS = "GET_HOTEL_LIST_SUCCESS",
  GET_HOTEL_LIST_START = "GET_HOTEL_LIST_START",
  GET_HOTEL_LIST_ERROR = "GET_HOTEL_LIST_ERROR",
  UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS"
}
